name: Create Release

# https://git-scm.com/book/en/v2/Git-Basics-Tagging
# git tag -a v1.4 -m "my version 1.4"
# git push origin v1.5
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
      version: ${{ steps.set_version.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - id: set_upload_url
      run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"
    - id: set_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
  build_ubuntu:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Build
      run: |
        # pip install -r requirements.txt
        pip install pytest pytest-cov
        pip install setuptools
        pip install tkcalendar
        pip install pillow
        pip install piexif
        pip install pyinstaller
        sh create_exe.sh
    - name: Upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./dist/application
        asset_name: imagesorter_ubuntu_${{ needs.create_release.outputs.version }}
        asset_content_type: application/octet-stream
  build_macos:
    runs-on: macos-latest
    needs: create_release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Build
      run: |
        # pip install -r requirements.txt
        pip install pytest pytest-cov
        pip install setuptools
        pip install tkcalendar
        pip install pillow
        pip install piexif
        pip install pyinstaller
        sh create_exe.sh
    - name: Upload
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./dist/application
        asset_name: imagesorter_mac_${{ needs.create_release.outputs.version }}
        asset_content_type: application/octet-stream
  build_windows:
    runs-on: windows-latest
    needs: create_release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        # pip install -r requirements.txt
        pip install pytest pytest-cov
        pip install setuptools
        pip install tkcalendar
        pip install pillow
        pip install piexif
        pip install pyinstaller
        sh create_exe.sh
    - name: Upload
      uses: actions/upload-release-asset@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./dist/application.exe
        asset_name: imagesorter_win_${{ needs.create_release.outputs.version }}.exe
        asset_content_type: application/octet-stream
